# pass a variable from one job to another
css-1:
  # when: manual
  stage: cache-stage1-shell
  # image: node:19-alpine3.16
  # artifacts:
  cache:
    untracked: true 
    # unprotect: true
    # key: "$CI_PIPELINE_ID"
    key: "$CI_BUILD_REF_NAME"
    when: 'always'
    policy: pull
    paths:
      - ./cache-stage-shell.env
  dependencies:
    - css-1
  script:
    - cat ./cache-stage-shell.env

# # pass a variable from one job to another
css-2:
  # when: manual
  stage: cache-stage2-shell
  # image: node:19-alpine3.16
  # artifacts:
  cache:
    untracked: true 
    # unprotect: true
    # key: "$CI_PIPELINE_ID"
    key: "$CI_BUILD_REF_NAME"
    when: 'always'
    policy: push
    paths:
      - ./cache-stage-shell.env
  script:
    - echo "testing456" > ./cache-stage-shell.env