# pass a variable from one job to another
csd-1:
  # when: manual
  stage: cache-stage1-dock
  # image: node:19-alpine3.16
  # artifacts:
  cache:
    untracked: true 
    unprotect: true
    # key: "$CI_PIPELINE_ID"
    key: "$CI_BUILD_REF_NAME"
    when: 'always'
    policy: pull
    paths:
      - ./cache-stage-dock.env
  dependencies:
    - csd-1
  script:
    - cat ./cache-stage-dock.env

# # pass a variable from one job to another
csd-2:
  # when: manual
  stage: cache-stage2-dock
  # image: node:19-alpine3.16
  # artifacts:
  cache:
    untracked: true 
    unprotect: true
    # key: "$CI_PIPELINE_ID"
    key: "$CI_BUILD_REF_NAME"
    when: 'always'
    policy: push
    paths:
      - ./cache-stage-dock.env
  script:
    - echo "testing456" > ./cache-stage-dock.env