# pass a variable from one job to another
cds-1:
  # when: manual
  stage: cache-dep-shell
  # image: node:19-alpine3.16
  # artifacts:
  cache:
    untracked: true 
    # unprotect: true
    # key: "$CI_PIPELINE_ID"
    key: "$CI_BUILD_REF_NAME"
    when: 'always'
    # policy: pull
    paths:
      - ./cache-dep-shell.env
  dependencies:
    - cds-2
  script:
    - cat ./cache-dep-shell.env

# # pass a variable from one job to another
cds-2:
  # when: manual
  stage: cache-dep-shell
  # image: node:19-alpine3.16
  # artifacts:
  cache:
    untracked: true 
    # unprotect: true
    # key: "$CI_PIPELINE_ID"
    key: "$CI_BUILD_REF_NAME"
    when: 'always'
    # policy: push
    paths:
      - ./cache-dep-shell.env
  script:
    - echo "testing456" > ./cache-dep-shell.env